export const TRUCKS_BRANDS = [
  { label: "All", value: "All" },
  { label: "Freightliner", value: "Freightliner" },
  { label: "International", value: "International" },
  { label: "Volvo", value: "Volvo" },
  { label: "Hino", value: "Hino" },
  { label: "Peterbilt", value: "Peterbilt" },
  { label: "Kenworth", value: "Kenworth" },
  { label: "Mack", value: "Mack" },
  { label: "Ford", value: "Ford" },
  { label: "Honda", value: "Honda" },
  { label: "GMC", value: "GMC" },
  { label: "Isuzu", value: "Isuzu" },
  { label: "Chevrolet", value: "Chevrolet" },
  { label: "Sterling", value: "Sterling" },
  { label: "Western Star", value: "Western Star" },
  { label: "+Other", value: "Other" },
];

export const TRAILER_BRANDS = [
  { label: "All", value: "All" },
  { label: "Hyundai", value: "Hyundai" },
  { label: "Di-Mond", value: "Di-Mond" },
  { label: "Great Dane", value: "Great Dane" },
  { label: "Utility", value: "Utility" },
  { label: "Manac", value: "Manac" },
  { label: "Trailmobile", value: "Trailmobile" },
  { label: "Wabash", value: "Wabash" },
  { label: "Fontaine", value: "Fontaine" },
  { label: "Wilson", value: "Wilson" },
  { label: "Trail King", value: "Trail King" },
  { label: "Stoughton", value: "Stoughton" },
  { label: "Vanguard", value: "Vanguard" },
  { label: "Other+", value: "Other" },
];
